const CONFIG = {
    introTitle: 'Huyền à, Hiếu nè:3!',
    introDesc: `Nếu cuộc sống làm e mệt mỏi từ ngày tới đêm,
    Thì a sẽ mang một chút êm đềm tới ngay,
    Hạ thì mặc mát chút cũng được,
    Đông thì khăn ấm,
    Ngoan mà nghe lời, ko thì ăn đấm^^`,
    btnIntro: 'HiHi',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Vẫn cứ là thích anh <33',
    btnNo: 'Không, Anh trai à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Mình gặp nhau nhé babe, Đồng ý thì call cho a nhé^^',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://m.me/larry.namthan' 
}
